create    table studenti (
          id number (10, 0) generated by default as identity not null unique,
          jmbag number (10) not null unique,
          ime varchar2 (20) not null,
          prezime varchar2 (255) not null,
          email varchar2 (20) not null unique
          );