drop      table trivie;

drop      table adrese;

drop      table korisnici;

create    table korisnici (
          id number generated by default as identity primary key,
          ime varchar2 (20) not null,
          prezime varchar2 (40) not null,
          email varchar2 (30) not null unique,
          pass varchar2 (10) not null,
          pozmob number not null,
          bromob number not null,
          spol number not null,
          datrod date not null,
          constraint ck_spol3 check (spol in (0, 1))
          );

create    table adrese (
          id number generated by default as identity primary key,
          idkorisnika number not null,
          adresa varchar2 (60) not null,
          kucbro number not null,
          dodbro varchar2 (10) not null,
          idmjesto number not null,
          idzup number not null
          );

create    table trivie (
          id number generated by default as identity primary key,
          idkorisnika number not null,
          ljubimci number not null,
          boja varchar2 (7) not null,
          film varchar2 (200) not null,
          program number not null,
          constraint ck_program check (program between 1 and 4)
          );

alter     table adrese add constraint adrese_fk1 foreign key (idkorisnika) references korisnici (id);

alter     table trivie add constraint trivie_fk1 foreign key (idkorisnika) references korisnici (id);

alter     table korisnici add constraint uk_broj unique (pozmob, bromob);